# Generated by Django 3.1.3 on 2021-04-26 14:46

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.PositiveIntegerField(help_text='Duration in number of seconds')),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 16, 58, 424751))),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.PositiveIntegerField(help_text='Duration in number of seconds')),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 16, 58, 424751))),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('participents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_time', models.PositiveIntegerField(help_text='Duration in number of seconds')),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2021, 4, 26, 20, 16, 58, 424751))),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
